# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ben's page
description: > # this means to ignore newlines until "baseurl:"
  My personal website
url: "https://benwhiting.github.io/" # the base hostname & protocol for your site
your_name: Ben Whiting
github_username:  BenWhiting

# Build settings
markdown: kramdown

#Theme settings
theme_mode: dark

social:
  - service: github
    username: BenWhiting
    link: https://github.com/BenWhiting
